swagger: "2.0"
info:
  title: "API Chat - Grupo 1"
  description: "API para um chat."
  version: "1.0.0"

host: "chat-grupo1.swagger.io"
basePath: "/v2"
schemes:
- "https"
- "http"

securityDefinitions:
  chat_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:mensagens: "adiciona mensagem"
      read:mensagens: "ler informação da mensagem"

      write:usuario: "adiciona usuario"
      read:usuario: "ler informações do usuario"

      write:chat: "adiciona um chat"
      read:chat: "ler informações do chat"

  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"

paths:
  /mensagens/:
    post:
      tags:
      - "Mensagens"
      summary: "Adiciona uma nova mensagem no chat"
      description: ""
      operationId: "addMensagem"
      consumes:
      - "application/json"
      - "application/xml"

      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Um objeto de mensagem"
        required: true
        schema:
          $ref: "#/definitions/Mensagem"
      responses:
        "201":
          description: "Created"
        "401":
          description: "Unauthorized"
      security:
      - chat_auth:
        - "write:mensagens"
        - "read:mensagens"

    get:
      tags:
      - "Mensagens"
      summary: "Retorna todas as mensagens do chat"
      description: "Retorna todas as mensagens do chat"
      operationId: "getMensagens"
      produces:
      - "application/json"

      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Mensagem"
        "401":
          description: "Unauthorized"

      security:
      - chat_auth:
        - "write:mensagens"
        - "read:mensagens"

  /usuarios/:
    get:
      tags:
      - "Usuários"
      summary: "Retorna todos os usuário ativos no chat"
      description: "Retorna todos os usuário ativos no chat"
      operationId: "getUsuariosAtivos"
      produces:
      - "application/json"

      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Usuario"
        
      security:
      - chat_auth:
        - "write:mensagens"
        - "read:mensagens"

    post:
      tags:
        - "Usuários"
      summary: "Adiciona um usuário"
      description: "Adiciona um usuário ao sistema de chat"
      operationId: "postUsuarios"
      produces:
      - "application/json"

      responses:
        "400":
          description: "bad request"
          
        "201":
          description: "Created"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Usuario"

      security:
      - chat_auth:
        - "write:usuario"
        - "read:usuario"

  /usuarios/{userId}:
    get:
      tags:
      - "Usuários"
      summary: "Retorna um usuário"
      description: "Retorna um usuário"
      operationId: "getUsuarioPorID"
      parameters:
        - name: "userId"
          in: "path"
          description: "ID of pet that needs to be fetched"
          required: true
          type: "integer"
          maximum: 10.0
          minimum: 1.0
          format: "int64"
      produces:
      - "application/json"

      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Usuario"
        "404":
          description: "Not Found"
      security:
      - chat_auth:
        - "write:mensagens"
        - "read:mensagens"

  /chat:
    get:
      tags:
        - "Chat"
      summary: "Busca chats"
      description: "Busca os chats"
      operationId: "get All chats"
      produces:
        - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Chat"
        "400":
          description: "Invalid status value"

  /chat/{chatId}:
    get:
      tags:
        - "Chat"
      parameters:
        - name: "chatId"
          in: "path"
          description: "ID of pet that needs to be fetched"
          required: true
          type: "integer"
          maximum: 10.0
          minimum: 1.0
          format: "int64"
      summary: "Busca um chat"
      description: "Busca os chats"
      operationId: "findChats"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Busca um chat"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Chat"
        "404":
          description: "Not Found"

  /chat/{chatId}/mensagens:
    get:
      tags:
      - "Chat"
      
      parameters:
        - name: "chatId"
          in: "path"
          description: "ID of pet that needs to be fetched"
          required: true
          type: "integer"
          maximum: 10.0
          minimum: 1.0
          format: "int64"
        - in: "query"
          name: "limit"
          description: "Limite para a carga de mensagens"
          required: false
          type: "integer"
          format: "int64"
      summary: "Busca as mensagens do chat"
      description: "Buscas as mensagens de um determinado chat"
      operationId: "findChatsMensagens"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Chat"
        

definitions:
  Mensagem:
    type: "object"
    xml:
      name: "Mensagem"
    properties:
      id:
        type: "integer"
        format: "int64"
      dataEnvio:
        type: "string"
        format: "date-time"
      mensagem:
        type: "string"
        format: "text"
      idChat:
        type: "integer"
        format: "int64"
      idUsarioEnviando:
        type: "integer"
        format: "int64"
  Usuario:
    type: "object"
    xml:
      name: "Usuario"
    properties:
      id:
        type: "integer"
        format: "int64"
      nomeUsuario:
        type: "string"
        format: "text"
  Chat:
    type: "object"
    xml:
      name: "Chat"
    properties:
      id:
        type: "integer"
        format: "int32"
      data:
        type: "string"
        format: "date-time"
      usuarioId:
        type: "integer"
        format: "int32"