swagger: "2.0"
info:
  title: "API Chat - Grupo 1"
  description: "API para um chat."
  version: "1.0.0"

host: "chat-grupo1.swagger.io"
basePath: "/v2"
schemes:
  - "https"
  - "http"

paths:
  /usuario:
    get:
      tags:
        - "Usuario"
      summary: "Retorna TODOS os USUARIOS registrados na plataforma de chat"
      description: ""
      operationId: "getUsers"
      parameters:
        - in: "query"
          name: "offset"
          description: "The number of items to skip before starting to collect the result set"
          required: false
          type: "integer"
          format: "int64"
        - in: "query"
          name: "limit"
          description: "The numbers of items to return"
          required: false
          type: "integer"
          format: "int64"
      produces:
        - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Resp_Usuario"
        "404":
          description: "Not Found"

    post:
      tags:
        - "Usuario"
      summary: "Adiciona UM novo USUÁRIO na plataforma de chat"
      description: ""
      operationId: "addUser"
      parameters:
        - in: "body"
          name: "body"
          description: "Um objeto de mensagem"
          required: true
          schema:
            $ref: "#/definitions/Body_Usuario"
      produces:
        - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Resp_Usuario"
        "404":
          description: "Not Found"

  /usuario/{userId}:
    get:
      tags:
        - "Usuario"
      summary: "Retorna os dados de UM USUÁRIO da plataforma de chat"
      description: ""
      operationId: "getUser"
      parameters:
        - in: "path"
          name: "userId"
          description: "ID of pet that needs to be fetched"
          required: true
          type: "integer"
          format: "int64"
      produces:
        - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Resp_Usuario"
        "404":
          description: "Not Found"

  /grupo:
    get:
      tags:
        - "Chat"
      summary: "Retorna TODOS os GRUPOS da plataforma de chat"
      description: ""
      operationId: "addMensagem3"
      parameters:
        - in: "query"
          name: "offset"
          description: "The number of items to skip before starting to collect the result set"
          required: false
          type: "integer"
          format: "int64"
        - in: "query"
          name: "limit"
          description: "The numbers of items to return"
          required: false
          type: "integer"
          format: "int64"
      produces:
        - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Resp_Usuario"
        "404":
          description: "Not Found"

    post:
      tags:
        - "Chat"
      summary: "Adiciona UM novo GRUPO na plataforma de chat"
      description: ""
      operationId: "addMensagem4"
      parameters:
        - in: "body"
          name: "body"
          description: "Um objeto de mensagem"
          required: true
          schema:
            $ref: "#/definitions/Resp_Usuario"
      produces:
        - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Resp_Chat"
        "404":
          description: "Not Found"

  /grupo/{groupId}:
    get:
      tags:
        - "Chat"
      summary: "Retorna os dados de UM GRUPO da plataforma de chat"
      description: ""
      operationId: "addMensagem5"
      parameters:
        - in: "path"
          name: "groupId"
          description: "ID of pet that needs to be fetched"
          required: true
          type: "integer"
          format: "int64"
      produces:
        - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Resp_Usuario"
        "404":
          description: "Not Found"

  /grupo/{groupId}/mensagem:
    get:
      tags:
        - "Chat"
      summary: "Retorna TODAS as MENSAGENS de um GRUPO específico da plataforma."
      description: ""
      operationId: "addMensagem6"
      parameters:
        - in: "path"
          name: "groupId"
          description: "ID of pet that needs to be fetched"
          required: true
          type: "integer"
          format: "int64"
        - in: "query"
          name: "offset"
          description: "The number of items to skip before starting to collect the result set"
          required: false
          type: "integer"
          format: "int64"
        - in: "query"
          name: "limit"
          description: "The numbers of items to return"
          required: false
          type: "integer"
          format: "int64"
      produces:
        - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Resp_GetAllMessagesFromGroup"
        "404":
          description: "Not Found"

  /grupo/{groupId}/usuario:
    get:
      tags:
        - "Chat"
      summary: "Retorna TODOS os USUÁRIOS de um GRUPO específico da plataforma"
      description: ""
      operationId: "addMensagem7"
      parameters:
        - in: "path"
          name: "groupId"
          description: "ID of pet that needs to be fetched"
          required: true
          type: "integer"
          format: "int64"
        - in: "query"
          name: "offset"
          description: "The number of items to skip before starting to collect the result set"
          required: false
          type: "integer"
          format: "int64"
        - in: "query"
          name: "limit"
          description: "The numbers of items to return"
          required: false
          type: "integer"
          format: "int64"
      produces:
        - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Resp_GetAllUserFromGroup"
        "404":
          description: "Not Found"

  /grupo/{groupId}/usuario/{userId}:
    post:
      tags:
        - "Chat"
      summary: "Adiciona UM usuário a um grupo GRUPO específico"
      description: ""
      operationId: "addMensagem10"
      parameters:
        - in: "path"
          name: "groupId"
          description: "ID of pet that needs to be fetched"
          required: true
          type: "integer"
          format: "int64"
        - in: "path"
          name: "userId"
          description: "ID of pet that needs to be fetched"
          required: true
          type: "integer"
          format: "int64"
      produces:
        - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Resp_ChatUserAdd"
        "404":
          description: "Not Found"
    delete:
      tags:
        - "Chat"
      summary: "Apaga UM usuario de um GRUPO específico"
      description: ""
      operationId: "addMensagem11"
      parameters:
        - in: "path"
          name: "groupId"
          description: "ID of pet that needs to be fetched"
          required: true
          type: "integer"
          format: "int64"
        - in: "path"
          name: "userId"
          description: "ID of pet that needs to be fetched"
          required: true
          type: "integer"
          format: "int64"
      produces:
        - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Resp_ChatOut"
        "404":
          description: "Not Found"

  /grupo/{groupId}/mensagem/{userId}:
    post:
      tags:
        - "Chat"
      summary: "Adiciona UMA mensagem referenciando seu GRUPO e AUTOR"
      description: ""
      operationId: "addMensagem8"
      parameters:
        - in: "path"
          name: "groupId"
          description: "ID of pet that needs to be fetched"
          required: true
          type: "integer"
          format: "int64"
        - in: "path"
          name: "userId"
          description: "ID of pet that needs to be fetched"
          required: true
          type: "integer"
          format: "int64"
        - in: "body"
          name: "body"
          description: "Um objeto de mensagem"
          required: true
          schema:
            $ref: "#/definitions/Body_ChatUserMensagem"
      produces:
        - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Resp_ChatUserMensagem"
        "404":
          description: "Not Found"

definitions:
  Body_Usuario:
    type: "object"
    properties:
      nickname:
        type: "string"
        format: "text"
      email:
        type: "string"
        format: "text"

  Resp_Usuario:
    type: "object"
    properties:
      date:
        type: "string"
        format: "date-time"
      mensagem:
        type: "string"
        format: "text"
      group_id:
        type: "integer"
        format: "numeric"
      user:
        type: "object"
        properties:
          user_id:
            type: "integer"
          user_name:
            type: "string"
          user_email:
            type: "string"

  Body_Chat:
    type: "object"
    properties:
      name:
        type: "string"
        format: "text"
  Resp_Chat:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
        format: "text"
      create_at:
        type: "string"
        format: "date-time"

  Resp_ChatIn:
    type: "object"
    properties:
      id_chat:
        type: "integer"
        format: "int32"
      id_user:
        type: "integer"
        format: "int32"
      create_at:
        type: "string"
        format: "date-time"
  Resp_ChatOut:
    type: "object"
    properties:
      message:
        type: "string"
        format: "text"

  Body_ChatUserMensagem:
    type: "object"
    properties:
      mensagem:
        type: "string"
        format: "text"
  Resp_ChatUserMensagem:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
      id_chat:
        type: "integer"
        format: "int32"
      id_user:
        type: "integer"
        format: "int32"
      mensagem:
        type: "string"
        format: "text"
      create_at:
        type: "string"
        format: "date-time"

  Resp_ChatUserAdd:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
      id_chat:
        type: "integer"
        format: "int32"
      id_user:
        type: "integer"
        format: "int32"
      create_at:
        type: "string"
        format: "date-time"

  Resp_GetAllMessagesFromGroup:
    type: "object"
    properties:
      date:
        type: "string"
        format: "date-time"
      mensagem:
        type: "string"
        format: "text"
      group_id:
        type: "integer"
        format: "int32"
      user:
        type: "object"
        properties:
          user_id:
            type: "integer"
          nickname:
            type: "string"
          email:
            type: "string"

  Resp_GetAllUserFromGroup:
    type: "object"
    properties:
      group_id:
        type: "integer"
        format: "int32"
      user:
        type: "object"
        properties:
          user_id:
            type: "integer"
          nickname:
            type: "string"
          email:
            type: "string"
